name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [ '3.5', '3.6', '3.7', 'pypy3' ]
    name: Run tests with Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install test dependencies
        run: pip install tox codecov
      - name: Run tests
        run: tox
